# Generated by Django 2.2.10 on 2020-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_camers', '0002_auto_20200213_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livecameras',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_camers.Country', to_field='name'),
        ),
    ]
